# Generated by Django 2.2.1 on 2019-09-08 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='additional_due_time',
            field=models.PositiveIntegerField(default=0, help_text="Additional task's due time in minutes."),
        ),
    ]
