# Generated by Django 2.2.1 on 2019-09-15 11:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workflows', '0002_task_additional_due_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('uuid', django_extensions.db.fields.ShortUUIDField(blank=True, editable=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='workflows.State')),
            ],
            options={
                'verbose_name_plural': 'Activities',
                'unique_together': {('slug', 'state')},
            },
        ),
        migrations.CreateModel(
            name='ActivityStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('uuid', django_extensions.db.fields.ShortUUIDField(blank=True, editable=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_status', to='workflows.Activity')),
            ],
            options={
                'verbose_name_plural': 'Activities status',
            },
        ),
        migrations.CreateModel(
            name='TaskActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('uuid', django_extensions.db.fields.ShortUUIDField(blank=True, editable=False, unique=True)),
                ('datetime', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_activities', to='workflows.Activity')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_activities', to='workflows.ActivityStatus')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_activities', to='workflows.Task')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='task_status_selected_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Task Activities',
                'unique_together': {('task', 'activity')},
            },
        ),
    ]
