# Generated by Django 2.2.1 on 2019-09-17 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0003_activity_activitystatus_taskactivity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskactivity',
            options={'ordering': ['created_at'], 'verbose_name_plural': 'Task Activities'},
        ),
        migrations.AlterField(
            model_name='activity',
            name='name',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='activity',
            name='slug',
            field=models.SlugField(max_length=70),
        ),
        migrations.AlterField(
            model_name='activity',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='workflows.State'),
        ),
        migrations.AlterField(
            model_name='activitystatus',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='workflows.Activity'),
        ),
        migrations.AlterField(
            model_name='activitystatus',
            name='name',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='activitystatus',
            name='slug',
            field=models.SlugField(max_length=70),
        ),
    ]
