# Generated by Django 2.2.1 on 2019-09-21 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0004_auto_20190917_1444'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created_at'], 'verbose_name': 'Task', 'verbose_name_plural': 'Tasks'},
        ),
    ]
