# Generated by Django 2.2.1 on 2020-06-11 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0006_job_activated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='due_datetime',
            field=models.DateTimeField(blank=True, help_text='The deadline to finish the task.', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='warning_datetime',
            field=models.DateTimeField(blank=True, help_text='Date and time to change the task to the warning status.', null=True),
        ),
    ]
